// Predictive Signals — Command Center & NOVA.

export const PREDICTIVE_SIGNALS = [
  {
    id: 'ps-1',
    agent: 'ARIA',
    signal: 'Post-ASCO abstract citation cascade accelerating',
    currentState: 'RASolute 302 plenary abstract cited in 47 follow-on publications in 3 weeks post-ASCO. Signal velocity at historic peak for any RevMed data package. Independent JCO editorial framing daraxonrasib as "a new standard of care" has been re-shared 1,200+ times across professional networks.',
    trajectory: 'rising',
    timeToImpact: '0–6 months',
    confidence: 'high',
    requiredAction: 'Equip MSL team with citation landscape summary and media roundup to use in academic center field visits. Capture KOL reactions before the narrative solidifies.',
    suggestedAction: { label: 'Open in ARIA', path: '/congress' },
  },
  {
    id: 'ps-2',
    agent: 'LUCA',
    signal: 'Borghaei sentiment velocity: −24 pts in 30 days',
    currentState: 'Hossein Borghaei (Tier 1, Fox Chase Cancer Center) alignment score dropped from 73 to 49 since ASCO. Two public posts questioning multi-selective advantage in G12C NSCLC. No MSL contact logged since May 15.',
    trajectory: 'declining',
    timeToImpact: '0–3 months',
    confidence: 'high',
    requiredAction: 'Prioritize MSL engagement. Schedule scientific exchange on multi-selective vs G12C-selective mechanistic differentiation within 2 weeks. Prepare FVQ framework and Borghaei-specific briefing document.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
  {
    id: 'ps-3',
    agent: 'NOVA',
    signal: 'RAS testing gap insight hitting recurrence threshold',
    currentState: 'Insight AI1 (RAS testing infrastructure gap) has now been sourced from 4 independent MSL reports across 3 regions — crossed the Prioritised threshold. ~40% of community oncologists lack comprehensive RAS/NGS profiling. Adoption will stall without testing infrastructure support.',
    trajectory: 'rising',
    timeToImpact: '0–6 months',
    confidence: 'high',
    requiredAction: 'Commission RAS testing readiness toolkit (CDx guide + payer reimbursement one-pager). Deploy to community oncology MSL team before NDA filing.',
    suggestedAction: { label: 'Review in NOVA', path: '/insights' },
  },
  {
    id: 'ps-4',
    agent: 'ARIA',
    signal: 'ESMO 2026 abstract deadline: 6 weeks',
    currentState: 'ESMO 2026 abstract submission window closes in 6 weeks. RevMed has no confirmed ESMO session yet. Daraxonrasib subgroup analyses and elironrasib doublet data are congress-ready. Competitor (divarasib) has 2 confirmed abstracts.',
    trajectory: 'rising',
    timeToImpact: '0–3 months',
    confidence: 'medium',
    requiredAction: 'Confirm ESMO abstract submission strategy for daraxonrasib subgroup data and zoldonrasib G12D signal. Brief MSL team on ESMO competitive landscape.',
    suggestedAction: { label: 'Open in ARIA', path: '/congress' },
  },
  {
    id: 'ps-5',
    agent: 'LUCA',
    signal: '2 emerging PDAC KOLs crossed engagement watch threshold',
    currentState: 'Two academic GI oncologists (mid-career, high publication velocity) have increased conference-speaking frequency by 55% vs prior 6 months. Both cite RASolute 302 in recent talks. Neither is on the current RevMed engagement list.',
    trajectory: 'rising',
    timeToImpact: '3–6 months',
    confidence: 'medium',
    requiredAction: 'Add to LUCA watch list. Assign regional MSL for initial outreach and scientific-exchange conversation before ESMO.',
    suggestedAction: { label: 'Open in LUCA', path: '/kol' },
  },
];
